version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - /usr/src/app/gadget_board_frontend_dist
      - /usr/src/app/static
    env_file: .env
    command: ./start.sh

  nginx:
    restart: always
    build: ./nginx_prod/
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    env_file: .env
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: